version: "3.3"

services:
  database:
    container_name: heatmap_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=mappro
      - POSTGRES_USER=mappro
    ports:
      - 5438:5432