# Generated by Django 3.2.7 on 2021-09-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
